version: "3"
services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
  web:
    image: jamanoja/flask-redis-py-app
    container_name: web
    ports:
      - "5000:5000"
    volumes:
       - .:/code
    depends_on:
      - redis