version: "3"
services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    deploy:
      placement:
        constraints:
          - node.role == manager
    networks:
      - webnet
  web:
    image: jamanoja/flask-redis-py-app
    container_name: web
    ports:
      - "5000:5000"
    volumes:
       - .:/code
    depends_on:
      - redis
    networks:
      - webnet
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
networks:
  webnet: